### ISSUE TITLE
Rename gem request

### ISSUE THREAD

**Issue by opoudjis** [metanorma/relaton-itu#10]
@andrew2net Naming this gem ituBib, when all the other gems are named -bib, is a very bad idea. Please seriously consider renaming the gem itubib.

Once you have decided whether to or not, I will add this gem to the relaton gemspec.

**Comment by andrew2net** [comment]
Will we rename all bib gems to `relaton-*` as @ronaldtse suggested?

**Comment by opoudjis** [comment]
Ah. Well, that's a question for @ronaldtse. As long as they're consistent. It's normally a breaking change, but this is a major change anyway because of the refactoring, so if there's going to be gem renaming, now is the time to do it.

**Comment by ronaldtse** [comment]
Yes, let’s do it!

**Comment by opoudjis** [comment]
@andrew2net nistbib has not been renamed yet; is the renaming of all relaton-* gems a separate work item?

**Comment by ronaldtse** [comment]
@opoudjis maybe -- someone just needs to do it all at once. We want to rename the repo and update gemspec.

**Comment by andrew2net** [comment]
@opoudjis I just dive into `isobib` now. If you need it I'll rename `nistbib` today.

**Comment by ronaldtse** [comment]
@andrew2net please just rename them all at once then. Do you have access?

**Comment by andrew2net** [comment]
I have the right to rename `nistbib`. Haven't check other gems yet.

**Comment by ronaldtse** [comment]
Sure, ping me if you need my help. In any case, you can change the `gemspecs` of all 👍
