### ISSUE TITLE
Fetching ITU references for the ITU Operational Bulletin

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/relaton-itu#15]
We have been working on the ITU Operational Bulletin (https://github.com/ituob/ituob.org , deployed to www.ituob.org).

In each issue of the OB, there is a list of recommendations we need to describe in the following format:

https://github.com/ituob/itu-ob-data/blob/a6eb00e1afa73de6b3951a9296cc89fbd9b5af8d/issues/1173/general.yaml#L9-L11

(There is only one code there for now, but there should be multiple.)

It should be rendered in a list like this:

```
ITU-T F.743.7 (05/2019): Requirements for big data enhanced visual surveillance services
ITU-T F.743.8 (05/2019): Requirements for cloud computing platform supporting a visual surveillance system
ITU-T F.743.9 (05/2019): Use-cases and requirements for multimedia CDN
ITU-T F.746.9 (05/2019): Requirements and architecture for indoor conversational robot system
ITU-T F.749.10 (05/2019): Requirements for communication service of civilian unmanned aerial vehicle
ITU-T H.230 (05/2019): Frame-synchronous control and indication signals for audiovisual systems
ITU-T H.243 (05/2019): Procedures for establishing communication between three or more audiovisual terminals using digital channels up to 1920 kbit/s
ITU-T H.626.5 (05/2019): Architecture for intelligent visual surveillance systems
ITU-T H.643.1 (05/2019): Architecture for deployment of information centric network
ITU-T H.644.1 (05/2019): Functional architecture for virtual content delivery networks
ITU-T H.783 (V2) (05/2019): Digital signage: Audience measurement services
ITU-T H.846 (05/2019): Conformance of ITU-T H.810 personal health system: Personal Health Devices interface Part 6: Personal Health Gateway
ITU-T H.849 (05/2019): Conformance of ITU-T H.810 personal health system: Personal Health Devices interface Part 9: Transcoding for Bluetooth Low Energy: Personal Health Devices 
ITU-T T.873 (05/2019): Information technology - Digital compression and coding of continuous-tone still images: Reference Software
```

How can I use Relaton to search for the ITU code:
* "ITU-T F.743.9 (05/2019)"
* "ITU-T H.783 (V2) (05/2019)"

?

ping @andrew2net 
cc @strogonoff

**Comment by andrew2net** [comment]
@ronaldtse the www.ituob.org uses Jekyll as geolexica.com does. Jekyll prebuilds pages before publishing them. So if we need to retrieve data from Relaton we should do in the step of issues YAML files generation.
I'm working on geolexica.com [issue](https://github.com/ISO-TC211/geolexica.com/issues/31) now. Seems it's the similar issue.

**Comment by ronaldtse** [comment]
@andrew2net yes it is a similar issue. However, ituob.com uses Jekyll plugins to deal with the data. We probably want to store the resulting Relaton files (YAML) in a local cache, and then access them through the Jekyll plugin.

**Comment by andrew2net** [comment]
@ronaldtse use the last version of `relaton` gem to fetch ITU code:
```
db = Relaton::Db.new 'cache', nil
item = db.fetch 'ITU-T F.743.9 (05/2019)'
item.title.detect { |t| t.type == 'main' }.title.content
=> "ITU-T F.743.9 (05/2019): Use-cases and requirements for multimedia CDN"
```

**Comment by ronaldtse** [comment]
Thanks @andrew2net !
