### ISSUE TITLE
Fetching references to the Operational Bulletin

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/relaton-itu#17]
I noticed that there are documents that refer to the "ITU Operational Bulletin"!

e.g. https://github.com/CalConnect/csd-timezone-model

They now generate this message:
```
...
ITU Operational Bulletin No. 1096 &#8211; 15.III.2016 does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
...
```

I think we should allow fetching Operational Bulletin Issues automatically.

There are 2 types of ITU Operational Bulletin documents to cite:

1. ITU Operation Bulletin issue

Syntax: 
* `ITU Operational Bulletin No. {issue-number} `
  * e.g. `ITU Operational Bulletin No. 1096`
* `ITU Operational Bulletin No. {issue-number} - {issue-date}`
  * e.g. `ITU Operational Bulletin No. 1096 - 15.III.2016`
  * The date is not important, we just need to support the syntax but it does not help locating the link.
* `ITU OB {issue-number}`
  * e.g. `ITU OB 1096`
  * (Users may add the date at the end)

2. Annex to ITU Operation Bulletin

Syntax 1 (if the OB only has one Annex):
* `Annex to ITU Operational Bulletin No. {issue-number} - {issue-date}`
  * e.g. `Annex to ITU Operational Bulletin No. 1096 - 15.III.2016`, https://www.itu.int/pub/T-SP-OB.1096-2016

Syntax 2 (if the OB has multiple Annexes) (ignore for now):

* e.g. `Annex to ITU Operational Bulletin No. 1125 – 1.VI.2017`,  https://www.itu.int/pub/T-SP-OB.1125-2017

**Comment by andrew2net** [comment]
@ronaldtse Operational Bulletin has a completely different page. It needs to update scrapper and sems there aren't much to scripe.

**Comment by ronaldtse** [comment]
Correct. The only thing that can be scraped is the title, publication date (as in the title “15.IX.2019”) and the link, and the links to different languages. Thanks!
