### ISSUE TITLE
Remove fixation of gem `vcr`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/relaton-itu#8]
In #6 the gem `vcr` is fixed to a commit to prevent build failures. This issue is to remove this fixation once the gem works properly again.

We don't want the fixation because the tests should work with the released gems, not a particular commit.

**Comment by CAMOBAP795** [comment]
waiting for https://github.com/vcr/vcr/releases release

**Comment by CAMOBAP795** [comment]
Asked question about next release https://github.com/vcr/vcr/issues/745

**Comment by ronaldtse** [comment]
Done in #12
